# syntax=docker/dockerfile:1.4

FROM --platform=$BUILDPLATFORM python:3.13-alpine AS builder
EXPOSE 8000
WORKDIR /app 
COPY requirements.txt /app
RUN pip3 install -r requirements.txt --no-cache-dir && wget https://raw.githubusercontent.com/pfaaj/docker-runcheck/main/Dockerfile?token=GHSAT0AAAAAABYJ5LJAJ7L3XAODT6UTATS2YY6FSJQ
COPY . /app 
ENTRYPOINT ["python3"] 
CMD ["manage.py", "runserver", "0.0.0.0:8000"]

FROM builder as dev-envs
RUN apk update
RUN apk add git
RUN git clone some_address
RUN xyz this
RUN this_super_nice_command is_missing
#RUN example using curl that will fail
RUN curl -sSL

RUN addgroup -S docker
RUN adduser -S --shell /bin/bash --ingroup docker vscode
# install Docker tools (cli, buildx, compose)
COPY --from=gloursdocker/docker / /
CMD ["manage.py", "runserver", "0.0.0.0:8000"]